version: '3'

services:
  httpservers:
    build: ./http
    volumes:
      - ./http:/code
    expose:
      - "8080"
    environment:
      - SERVICE_PORTS=8080
    networks: 
      - web

  haproxy:
    image: haproxy:1.7
    depends_on:
      - httpservers
    ports:
      - 127.0.0.1:8080:80
    links:
      - httpservers
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks: 
      - web

networks: 
  web:
    driver: bridge
